### ISSUE TITLE
Syntax errors in CTL 

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sensorml10#1]
Executing tests on the SensorML implementation found at the following URL:  http://sensorweb.demo.52north.org/52n-sos-webapp-4.0.0-Beta1/sos/kvp?request=DescribeSensor&service=SOS&version=2.0.0&procedure=http://www.example.org/sensors/101&procedureDescriptionFormat=http://www.opengis.net/sensorML/1.0.1
      responseType: DescribeSensorResponses
Testing sml:SchemaValidationD type Mandatory in Test Mode with defaultResult Pass (s0010/d1e118_1)...
         Assertion: The provided SensorML complies with the SensorML 1.0.1 Implementation Specification.
         Executing a request for getting the context of the provided DescribeSensorResponses from "http://sensorweb.demo.52north.org/52n-sos-webapp-4.0.0-Beta1/sos/kvp?request=DescribeSensor&service=SOS&version=2.0.0&procedure=http://www.example.org/sensors/101&procedureDescriptionFormat=http://www.opengis.net/sensorML/1.0.1".
Jul 17, 2014 10:59:04 AM com.occamlab.te.parsers.XMLValidatingParser parse
SEVERE: error parsing
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1008; The element type "HR" must be terminated by the matching end-tag "</HR>".
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at com.occamlab.te.parsers.XMLValidatingParser.parse(XMLValidatingParser.java:240)
	at com.occamlab.te.parsers.XMLValidatingParser.parse(XMLValidatingParser.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.occamlab.te.TECore.parse(TECore.java:1859)
	at com.occamlab.te.TECore.parse(TECore.java:1775)
	at com.occamlab.te.TECore.request(TECore.java:1375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
	at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
	at net.sf.saxon.expr.PathExpression.iterate(PathExpression.java:848)
	at net.sf.saxon.sort.DocumentSorter.iterate(DocumentSorter.java:84)
	at net.sf.saxon.instruct.CopyOf.processLeavingTail(CopyOf.java:292)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
	at net.sf.saxon.instruct.DocumentInstr.evaluateItem(DocumentInstr.java:282)
	at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:295)
	at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:341)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:542)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
	at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
	at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
	at net.sf.saxon.Controller.transform(Controller.java:1560)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:517)
	at com.occamlab.te.TECore.executeTest(TECore.java:660)
	at com.occamlab.te.TECore.callTest(TECore.java:755)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sf.saxon.functions.ExtensionFunctionCall.invokeMethod(ExtensionFunctionCall.java:533)
	at net.sf.saxon.functions.ExtensionFunctionCall.call(ExtensionFunctionCall.java:256)
	at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:147)
	at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:352)
	at net.sf.saxon.instruct.SimpleContentConstructor.evaluateItem(SimpleContentConstructor.java:261)
	at net.sf.saxon.instruct.ValueOf.processLeavingTail(ValueOf.java:233)
	at net.sf.saxon.instruct.Choose.processLeavingTail(Choose.java:625)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
	at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
	at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
	at net.sf.saxon.Controller.transform(Controller.java:1560)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:517)
	at com.occamlab.te.TECore.executeTest(TECore.java:660)
	at com.occamlab.te.TECore.execute_test(TECore.java:347)
	at com.occamlab.te.TECore.execute_suite(TECore.java:390)
	at com.occamlab.te.TECore.execute(TECore.java:252)
	at com.occamlab.te.Test.main(Test.java:354)

Fatal Parsing error at line 1, column 1008:
  The element type "HR" must be terminated by the matching end-tag "</HR>".
1 validation error detected.

         FAILURE: Missing or invalid response entity.
      Test sml:SchemaValidationD Failed
   Test sml:Main Failed
Suite sml:suite Failed

**Comment by bermud** [comment]
CTL was fixed, including escaping & and correct path for schema files
